/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
import * as reactQuery from "@tanstack/react-query";
import { useBellemansContext, BellemansContext } from "./bellemansContext";
import type * as Fetcher from "./bellemansFetcher";
import { bellemansFetch } from "./bellemansFetcher";

export type QueryOperation = {
  path: string;
  operationId: never;
  variables: unknown;
};
