/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
export type CallToActionResponse = {
  url: string;
  text: string;
};

export type CallToActionSubSectionResponse = {
  title: string;
  description: string;
  callToActionResponse: CallToActionResponse;
};

export type GetAllPagesResponse = {
  pages: PageResponse[];
};

export type GetPageByNameResponse = {
  page: PageResponse2;
};

export type HeaderSectionResponse = {
  /**
   * @format uuid
   */
  id: string;
  title: string;
  description: string;
  /**
   * @format int32
   */
  order: number;
  primaryCallToActionResponse: CallToActionResponse;
  secondaryCallToActionResponse: CallToActionResponse;
};

export type ImageSectionResponse = {
  /**
   * @format uuid
   */
  id: string;
  imageUrl: string;
  /**
   * @format int32
   */
  order: number;
};

export type PageResponse = {
  /**
   * @format uuid
   */
  id: string;
  name: string;
  title: string;
  pageSections: PageSectionResponse[];
  headerSections: HeaderSectionResponse[];
  imageSections: ImageSectionResponse[];
  servicesSections: ServicesSectionResponse[];
};

export type PageResponse2 = {
  /**
   * @format uuid
   */
  id: string;
  name: string;
  title: string;
  pageSections: PageSectionResponse[];
  headerSections: HeaderSectionResponse[];
  imageSections: ImageSectionResponse[];
  servicesSections: ServicesSectionResponse2[];
};

export type PageSectionResponse = {
  /**
   * @format uuid
   */
  id: string;
  /**
   * @format int32
   */
  order: number;
};

export type ProblemDetails = {
  type?: string | null;
  title?: string | null;
  /**
   * @format int32
   */
  status?: number | null;
  detail?: string | null;
  instance?: string | null;
};

export type ServicesSectionResponse = {
  /**
   * @format uuid
   */
  id: string;
  /**
   * @format int32
   */
  order: number;
  title: string;
  firstCallToActionSubSectionResponse: CallToActionSubSectionResponse;
  secondCallToActionSubSectionResponse: CallToActionSubSectionResponse;
};

export type ServicesSectionResponse2 = {
  /**
   * @format uuid
   */
  id: string;
  /**
   * @format int32
   */
  order: number;
  title: string;
  firstCallToActionSubSectionResponse: CallToActionSubSectionResponse;
  secondCallToActionSubSectionResponse: CallToActionSubSectionResponse;
};
