/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
export type GetAllPagesResponse = {
  pages: PageResponse[];
};

export type MappedHeaderSection = {
  title?: string;
  description?: string;
  /**
   * @format uuid
   */
  id?: string;
  /**
   * @format int32
   */
  order?: number;
};

export type MappedImageSection = {
  imageUrl?: string;
  /**
   * @format uuid
   */
  id?: string;
  /**
   * @format int32
   */
  order?: number;
};

export type PageResponse = {
  name: string;
  title: string;
  headerSections: MappedHeaderSection[];
  imageSections: MappedImageSection[];
};

export type ProblemDetails = {
  type?: string | null;
  title?: string | null;
  /**
   * @format int32
   */
  status?: number | null;
  detail?: string | null;
  instance?: string | null;
};
