/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DynamicImport } from './routes/dynamic'
import { Route as AboutImport } from './routes/about'
import { Route as PagenameImport } from './routes/$pagename'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const DynamicRoute = DynamicImport.update({
  id: '/dynamic',
  path: '/dynamic',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const PagenameRoute = PagenameImport.update({
  id: '/$pagename',
  path: '/$pagename',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$pagename': {
      id: '/$pagename'
      path: '/$pagename'
      fullPath: '/$pagename'
      preLoaderRoute: typeof PagenameImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/dynamic': {
      id: '/dynamic'
      path: '/dynamic'
      fullPath: '/dynamic'
      preLoaderRoute: typeof DynamicImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$pagename': typeof PagenameRoute
  '/about': typeof AboutRoute
  '/dynamic': typeof DynamicRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$pagename': typeof PagenameRoute
  '/about': typeof AboutRoute
  '/dynamic': typeof DynamicRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$pagename': typeof PagenameRoute
  '/about': typeof AboutRoute
  '/dynamic': typeof DynamicRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$pagename' | '/about' | '/dynamic'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$pagename' | '/about' | '/dynamic'
  id: '__root__' | '/' | '/$pagename' | '/about' | '/dynamic'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PagenameRoute: typeof PagenameRoute
  AboutRoute: typeof AboutRoute
  DynamicRoute: typeof DynamicRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PagenameRoute: PagenameRoute,
  AboutRoute: AboutRoute,
  DynamicRoute: DynamicRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$pagename",
        "/about",
        "/dynamic"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$pagename": {
      "filePath": "$pagename.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/dynamic": {
      "filePath": "dynamic.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
