/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HomeDraftImport } from './routes/homeDraft'
import { Route as PagenameImport } from './routes/$pagename'

// Create/Update Routes

const HomeDraftRoute = HomeDraftImport.update({
  id: '/homeDraft',
  path: '/homeDraft',
  getParentRoute: () => rootRoute,
} as any)

const PagenameRoute = PagenameImport.update({
  id: '/$pagename',
  path: '/$pagename',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$pagename': {
      id: '/$pagename'
      path: '/$pagename'
      fullPath: '/$pagename'
      preLoaderRoute: typeof PagenameImport
      parentRoute: typeof rootRoute
    }
    '/homeDraft': {
      id: '/homeDraft'
      path: '/homeDraft'
      fullPath: '/homeDraft'
      preLoaderRoute: typeof HomeDraftImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/$pagename': typeof PagenameRoute
  '/homeDraft': typeof HomeDraftRoute
}

export interface FileRoutesByTo {
  '/$pagename': typeof PagenameRoute
  '/homeDraft': typeof HomeDraftRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/$pagename': typeof PagenameRoute
  '/homeDraft': typeof HomeDraftRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$pagename' | '/homeDraft'
  fileRoutesByTo: FileRoutesByTo
  to: '/$pagename' | '/homeDraft'
  id: '__root__' | '/$pagename' | '/homeDraft'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  PagenameRoute: typeof PagenameRoute
  HomeDraftRoute: typeof HomeDraftRoute
}

const rootRouteChildren: RootRouteChildren = {
  PagenameRoute: PagenameRoute,
  HomeDraftRoute: HomeDraftRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/$pagename",
        "/homeDraft"
      ]
    },
    "/$pagename": {
      "filePath": "$pagename.tsx"
    },
    "/homeDraft": {
      "filePath": "homeDraft.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
